// This file is generated by Slice Machine. Update with care!

import Conteudo from './Conteudo';
import Terminal from './Terminal';
import Teste from './Teste';

export {
	Conteudo,
	Terminal,
	Teste,
};

export const components = {
	conteudo: Conteudo,
	terminal: Terminal,
	teste: Teste,
};
